### ISSUE TITLE
关于屏幕问题

### ISSUE THREAD

**Issue by fly-summer** [zsakvo/hp-348-g5-hackintosh#3]
首先收藏了，等不用他来办公了就试试。
其次我想问下，这款能换屏幕吗，实在受不了到处泛着白光的TN屏幕。
再次感谢

**Comment by zsakvo** [comment]
屏幕我也受不了，确实难受，理论上应该是可以换 1080p 的，但是具体的没尝试了……

**Comment by maYunLaoXi** [comment]
你们的不是1080的屏幕的吗？我这台是1920x1080的，显卡是UHD 620 cpu i5-8265u ,怪不得我用这个引导不行啊

**Comment by zsakvo** [comment]
1366x768，uhd620 i5-8265uc。
安装的时候你可以用黑果小兵的自带的默认 clover 进行安装 装好以后覆盖引导即可
