### ISSUE TITLE
网卡问题

### ISSUE THREAD

**Issue by Aleting** [zsakvo/hp-348-g5-hackintosh#4]
原装的网卡吗？能用吗这台电脑的网卡

**Comment by zsakvo** [comment]
Intel 的无线网卡全球无解，自行替换 dw1820a 可解。这机子没白名单，算是比较幸运的。
不过 dw1820a 这卡虽然便宜，但是有点一言难尽……
不想换的话可以去买个 USB 的，三十多块钱，支持 WiFi5，也能凑活用

**Comment by Aleting** [comment]
算了公司电脑，还是不要太作死，攒钱买苹果吧

**Comment by zsakvo** [comment]
加油咯
