### ISSUE TITLE
同款笔记本，为什么卡在了白苹果那里？

### ISSUE THREAD

**Issue by maYunLaoXi** [zsakvo/hp-348-g5-hackintosh#5]
卡在了白苹果那里？用的系统是10.15.4的，15.1暂时还没有找到下载

**Comment by zsakvo** [comment]
需要详细的 日志 才知道原因呀……
况且后续是可以升级到 10.15.4 的……自行更新 clover 和 相关驱动即可 :)

**Comment by maYunLaoXi** [comment]
> 需要详细的 日志 才知道原因呀……
> 况且后续是可以升级到 10.15.4 的……自行更新 clover 和 相关驱动即可 :)

 看不到日志，（不知道哪里看）进了clover选择系统那里有两个，一个mac安装的，点进去，跳到一个白苹果界面一直不动

**Comment by zsakvo** [comment]
建议去 远景 以及 tonymacx86 看一下最基础的教程（比如如何打开 啰嗦模式）

**Comment by maYunLaoXi** [comment]
> 建议去 远景 以及 tonymacx86 看一下最基础的教程（比如如何打开 啰嗦模式）

有不有10.15.1的迅雷下载，都是网盘的，8个G下半个月都下不完

**Comment by maYunLaoXi** [comment]
> 需要详细的 日志 才知道原因呀……
> 况且后续是可以升级到 10.15.4 的……自行更新 clover 和 相关驱动即可 :)

折腾了好些天，可能是我这个机的硬盘问题。请问你的是什么牌子和型号的硬盘？

**Comment by zsakvo** [comment]
一般而言和硬盘关系，只要你不是三丧的 pm981(a) 基本就没什么问题
我的自带的事三丧的一块 128g 的固态（型号忘了），但是系统装在了自购的一块惠普的固态上了……

**Comment by maYunLaoXi** [comment]
> 一般而言和硬盘关系，只要你不是三丧的 pm981(a) 基本就没什么问题
> 我的自带的事三丧的一块 128g 的固态（型号忘了），但是系统装在了自购的一块惠普的固态上了……

你是说和硬盘没有关系吗？我的本是一个镁光的nvme固态，问了一些网友说是有个别镁光的硬盘没有办法按装黑苹果。请问你买的那块是惠普什么型号的硬盘？还有就是你的电脑有两个硬盘接口？看来我们这两款电脑差异还是有点大

**Comment by zsakvo** [comment]
镁光不是很清楚 没研究过。
我把之前的自带的机械硬盘拔了，换的固态

**Comment by maYunLaoXi** [comment]
> 镁光不是很清楚 没研究过。
> 我把之前的自带的机械硬盘拔了，换的固态

那行，你买的那块是惠普什么型号的硬盘？我照着买一块试一下

**Comment by zsakvo** [comment]
其实说实话，我自己不是很建议在这本子上花钱折腾。
我自己现在也是直接入了白果。
我买的是 `惠普（HP） 500G SSD 固态硬盘 SATA3.0 接口 S700 系列` 这个。

**Comment by maYunLaoXi** [comment]
> 其实说实话，我自己不是很建议在这本子上花钱折腾。
> 我自己现在也是直接入了白果。
> 我买的是 `惠普（HP） 500G SSD 固态硬盘 SATA3.0 接口 S700 系列` 这个。

我其实是白果用户。这台电脑是公司的，打算是折腾一下，看能不能装上。
因为公司没有办法保证员工个人财物安全，每天背自己的15寸的电脑来回好累。特别是夏天还很热。
你的这块硬盘是stata的，我拆开电脑看了一下我这台是没有sata接口的。只有一个m.2接口。
我可能买个便宜的m.2最后一试。

**Comment by zsakvo** [comment]
那看起来差别还是蛮大的，怪不得装不上。
自己背着确实挺沉的 :)
